### ISSUE TITLE
What is the 'batch_sim'?

### ISSUE THREAD

**Issue by medivhna** [sciencefans/Quality-Aware-Network#1]
I noticed that there is a [1,1,1,1] input 'sim' in your network? 
```
input: "sim"
input_dim: 1
input_dim: 1
input_dim: 1
input_dim: 1
```
What is this input specifically?

**Comment by liuyuisanai** [comment]
@medivhna We add a contrastive loss in this network to constrain inner-class distance. The input 'sim' is its label (always = 1). You can remove it along with contrastive loss (with about 0.9% drop of accuracy).
