### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ghost** [sciencefans/Quality-Aware-Network#14]
issue

**Comment by skJack** [comment]
same question

**Comment by gceboh** [comment]
An unofficial re-implementation repo: [PyTorch-QAN](https://github.com/yxgeee/PyTorch-QAN).
It attempted to reproduce the paper `Quality Aware Network for Set to Set Recognition` (video-based person re-identification only). Though different network structure is used, the main idea is preserved.
