### ISSUE TITLE
About training batch size on LPW

### ISSUE THREAD

**Issue by lxc86739795** [sciencefans/Quality-Aware-Network#3]
From the train_PQAN_image.prototxt, we can see the shape of input batch
input: "data"
input_dim: 24
input_dim: 3
input_dim: 224
input_dim: 224

input: "label"
input_dim: 24
input_dim: 1
input_dim: 1
input_dim: 1

input: "sim"
input_dim: 1
input_dim: 1
input_dim: 1
input_dim: 1

I guess for one input batch, the "data" contains 3 groups as the anchor, the positive, and the negtive. Each group has 8 images with the same face ID as the "label".
The "sim" is a binary number to denote the whether group 1 and group 2 have the same ID.
So in fact the batch size for training is 1.
Is my understanding right?

**Comment by liuyuisanai** [comment]
@lxc86739795 You are right. Two things need to be mentioned:
- 'sim' should be 1 constantly during training. Here we use an additional `contrastive loss` to enhance the cos distance between seqA and seqP, and `sim` is the label for it.
- Batch size is 1 in regard to sequence representation and 24 to image representation during training.
